### ISSUE TITLE
API for leads verified after epoch or new verified leads created after an epoch

### ISSUE THREAD

**Issue by jitendraag** [coronasafe/life-data#9]
Endpoint: https://life-pipeline.coronasafe.network/api/resources?state=state_name&district=district_name&resource=resource_type&epoch=unixepoch

Looking to add an optional parameter to this API so that queries like (verified in last 1 day) can be powered.

This can also be used for a proposed Telegram bot that will send new verified leads for a state to respective Telegram group.

**Comment by khavinshankar** [comment]
@jitendraag should the epoch be a date or a number?
